/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general-purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    checkstyle
    java
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("data"))
        }
        resources {
            setSrcDirs(listOf("data"))
        }
    }
}

tasks.withType(Checkstyle::class.java).configureEach {
    minHeapSize = "200m"
    maxHeapSize = "4g"
    maxWarnings = 0  // Fail on any warning
    maxErrors = 0    // Fail on any error
    source(project.sourceSets.main.get().allSource.matching {
        exclude("**/*.psd", "**/*.PSD")
    })
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

var stagingFolder = File(project.layout.buildDirectory.get().toString(), "staging")

dependencies {
    implementation("com.puppycrawl.tools:checkstyle:13.4.0")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// mm-data only produces the zipped artifacts (unit files, RATs, planetary systems)
// that the consuming projects (MegaMek, MegaMekLab, MekHQ) substitute for the loose
// source files. The consumers' own `stageDataFiles` tasks now copy the remaining
// loose data directly out of `mm-data/data`, so there is no intermediate staging
// copy here. Removing that copy avoids moving ~900 MB of image/board data twice per
// build; see each consumer's build.gradle for the split, incremental sync tasks.

tasks.register<Zip>("unitFilesZip") {
    description = "Creates zip archives of all the unit file folders (excluding loose .txt and .xml files)."
    group = "build"
    destinationDirectory.set(File(stagingFolder, "mekfiles"))
    archiveFileName.set("unit_files.zip")
    from("data/mekfiles") {
        exclude("*.txt")
        exclude("*.xml")
        exclude("*.cache")
    }
}

tasks.register<Zip>("ratZip") {
    description = "Creates a zip archive of all the random assignment tables."
    group = "build"
    from("data/rat")
    destinationDirectory.set(File(stagingFolder, "rat"))
    archiveFileName.set("rat_default.zip")
}

tasks.register<Zip>("canonSystemZip") {
    description = "Creates a zip archive of canon planetary systems."
    group = "build"
    from("data/universe/planetary_systems/canon_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("canon_systems.zip")
}

tasks.register<Zip>("connectorSystemZip") {
    description = "Creates a zip archive of connector systems planetary systems."
    group = "build"
    from("data/universe/planetary_systems/connector_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("connector_systems.zip")
}
